version: "3.3"

services:
  zookeeper:
    platform: linux/arm64
    image: confluentinc/cp-zookeeper:7.4.0
    restart: on-failure
    hostname: zookeeper
    container_name: sse_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - docker-network
    volumes:
      - ./volume/zookeeper/data:/var/lib/zookeeper/data
      - ./volume/zookeeper/log:/var/lib/zookeeper/log

  kafka:
    platform: linux/arm64
    image: confluentinc/cp-kafka:7.4.0
    restart: on-failure
    hostname: kafka
    container_name: sse_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - docker-network
    volumes:
      - ./volume/kafka/data:/var/lib/kafka/data

  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    restart: on-failure
    hostname: dynamodb
    container_name: sse_dynamodb-local
    ports:
      - "8111:8111"
    networks:
        - docker-network
    volumes:
      - "./volume/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    command: -jar DynamoDBLocal.jar -sharedDb -port 8111 -dbPath ./data

networks:
  docker-network:
    driver: bridge
